# Generated by Django 5.1.3 on 2024-11-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='donor_name',
        ),
    ]
